print('  //A    //N   N  //DDDD   //RRRR   //EEEEE  //IIIII')
print(' //A A   //NN  N  //D   D  //R   R  //E        //I  ')
print('//A   A  //N N N  //D   D  //R   R  //E        //I  ')
print('//AAAAA  //N  NN  //D   D  //RRRR   //EEE      //I  ')
print('//A   A  //N   N  //D   D  //R R    //E        //I  ')
print('//A   A  //N   N  //D   D  //R  R   //E        //I  ')
print('//A   A  //N   N  //DDDD   //R   R  //EEEEE  //IIIII')